### ISSUE TITLE
Initial Users for feedback meetings

### ISSUE THREAD

**Issue by mhdawson** [nodejs/user-feedback#12]
As part of the mandate we should be getting together with end users to get their feedback.

I'm opening this issue to start the discussion on how we identify an initial set of users to invite.  I have a few ideas, but before I talk to them about it I'd like us to discuss and agree on the process for identifying and inviting people to be on the list of those that will be invited to the initial meetings.

**Comment by dshaw** [comment]
At #6, we discussed 3 potential User Feedback meetings:
* [@dshaw] GoPro is interested in hosting a Meetup in January in San Mateo, CA. Let's do in-person feedback around the Node.js Benchmarking survey (https://github.com/nodejs/community-committee/issues/153). Since this is in the South Bay, it will probably be a largely enterprise crowd.
* [@williamkapke] TENTATIVE at 2018-01-12 meeting: Choosing Node.js feedback session. Invite companies who have recently chosen Node.js and companies evaluating Node.js.
* [@mhdawson] At 2017-02-09 meeting: Enterprise user feedback targeting folks who want to join us to provide regular feedback.

**Comment by dshaw** [comment]
@mhdawson Can we use the alias user-feedback@nodejs.org instead so we don't create confusion for folks who don't know what io.js is?

**Comment by mhdawson** [comment]
@dshaw I have not idea how we set up a nodejs.org one.  @rvagg I'm gueesing you do can you fill me in ?

**Comment by rvagg** [comment]
@mhdawson make the @iojs.org alias and I'll loop you in via email to getting the alias set up to make it work. As with other addresses we'll just use the @iojs.org address for management and transparency with @nodejs.org as a forwarding.

**Comment by mhdawson** [comment]
Final version of email after discussion with @dshaw.  @nodejs/community-committee @nodejs/tsc FYI in case you get asked about this.  

**End User Feedback - Looking for Participants**

The Node.js end user feedback team (NEUF) will be working to gather feedback from end users through a number of different channels.

One of those channels will be live discussion either in person or on-line.  We are starting to put together a list of businesses who:

* are using Node.js for their production systems
* use Node.js as part of their tooling 
* are evaluating Node.js as a potential technology
* have recently chosen Node.js and are just getting started
* would like to use Node.js but face obstacles in being able to do so

If you would like to get involved and participate regularly (currently thinking is every 2 months or quarterly) please email user-feedback@nodejs.org

**Comment by dshaw** [comment]
@rvagg Thank you, sir.

**Comment by dshaw** [comment]
@mhdawson This would be great to incorporate in the README too.

**Comment by mhdawson** [comment]
Issue asking for participants:

https://github.com/nodejs/user-feedback/issues/20

tweet publicizing  https://twitter.com/mhdawson1/status/941346197796667393

Have also asked that it been retweeted by foundation account.

**Comment by mhdawson** [comment]
PR to add to README.md https://github.com/nodejs/user-feedback/pulls

**Comment by DiegoZoracKy** [comment]
@dshaw, @mhdawson, it seems that this survey will get a good attention and possibly a great number of responses. I'm wondering if it could be an opportunity to get the initial answers for: **who we are**, **where we are** and **how we are using Node.js**. It could be a section, not required, and saying explicitly that this info would be used openly. Targeting only the ones who are ok about sharing this data.

Without thinking specifically about what was proposed here, as npe: [/nodejs/community-committee/issues/184](https://github.com/nodejs/community-committee/issues/184), I believe this kind of data, specially about the geolocation, can be great to extract some good insights about the pulse of Node.js worldwide and locally. We can identify some patterns of the use of Node.js by region, and how those groups are concentrated.

Also, are the questions that are being formulated open somewhere, for others to contribute?

**Comment by williamkapke** [comment]
Heads up: I need to be onsite with a client when the January meeting is planned and unable to attend.

**Comment by dshaw** [comment]
@williamkapke Thanks for the heads-up. I'll schedule the 2018-01-12 meeting around the same time as I run the 2017-12-29 meeting. Since you will not be available, let's put your topic on the back burner until you're available to organize.

**Comment by mhdawson** [comment]
@DiegoZoracKy just catching up and as survey is already out a bit late to address your questions.  The draft for the questions were public in: https://github.com/nodejs/benchmarking/issues/136

In terms of asking more info, it might make sense at this point to come up with a new set of survey questions to capture information that you mention ?

**Comment by DiegoZoracKy** [comment]
@mhdawson If the survey was yet to be released, I believe it wouldn't be needed too much effort to add some new questions. Maybe it won't be good to invest right now on a new survey just to address these questions. Let's mature the idea first and see how this data (*who we are*, *where we are* and *how we are using Node.js*) can be valuable to the community.

**Comment by mhdawson** [comment]
@DiegoZoracKy ok sounds good.
