### ISSUE TITLE
Schedule Enterprise Feedback Group Meeting

### ISSUE THREAD

**Issue by ahmadnassri** [nodejs/user-feedback#122]
- Tie-in with next release date
- Suggested Date: **April 25th @ 1PM EST**
- Action Items:
  - [x] Email / Newsletter to Enterprise members, advise on release date & notify of meeting 
  - [x] Calendar Invites for members
  - [x] if latest survey is ready, include in email
  - [x] Tie-in with Local Meetup call-to-action

**Comment by ktrott** [comment]
I'm not sure if this is the appropriate place to ask this so feel free to redirect if not.

Where is it documented who the Enterprise members are? How does one join if interested?

Some of the links from the README of this repo go to old issues or a different repo that is not maintained: https://github.com/nodejs/enterprise-advisory-group

**Comment by dshaw** [comment]
@ktrott: Totally appropriate place to call that out. Thank you.

**Comment by ahmadnassri** [comment]
completed in #144
