### ISSUE TITLE
Draft Blog post for Enterprise Focus Group

### ISSUE THREAD

**Issue by ahmadnassri** [nodejs/user-feedback#123]
Discuss the "Why" "What" & "How" for introducing the Enterprise context.

### Who’s it for?

> (Intended audience)

- Companies building on, or using Node.js and it's ecosystem with large development teams (50 to 100+) *OR*
- Companies building on, or using Node.js and it's ecosystem with large technology footprint (50+ projects)
- Need to be specific about ecosystem: namely the Node.js project and it's directly connected projects, excluding 3rd party developed frameworks, libraries and tools.
  - While feedback on those 3rd party solutions might be useful and educational, the core focus of where Enterprise Feedback should be is for the projects that the Node.js project directly influences

### Primary Message

> What’s the primary message you want that audience to come away with?

- Encourage contribution _(in all it's forms)_ at the business level _(vs. individual level)_ to the Node.js Open Source Projects.
- Gather feedback and insights from challenges faced by closed-source projects using Node.js behind large businesses that otherwise is not immediately visible to the Open Source community
  - Impact of change in the OSS domain to business operations
  - Cost of adoption vs. Total Cost of Ownership for Node.js application development
  - Usage of, and impact of Node.js in driving business revenue, or cost effort reductions.

### Summary of project

> (any more details on the above)

The growth and success of Node.js is in large part, due to the contribution of passionate individuals, as part of the daily efforts at work in large enterprise companies. Those businesses benefit from both the individual effort and the success of Node.js itself, a more engaged conversation with businesses themselves and the technology leaders of those business, will only result in further maximizing the ROI for their already deep investments in Node.js

_using my own blurb here, from a panel on Open Source in Enterprise as reference for those key points:_

> In today’s world, the adoption of Open Source software in the enterprise is a key growth and transformational factor for a lot of companies. There are so many facets changing from where we were as an industry 10-15 years ago to where we are today.  The biggest leading indicator of why Open Source is valuable to enterprises is in the areas of team members. You’ve much opportunity to scale and grow your business when your own developer community has a bigger community umbrella around it.

> The idea of companies having a moral obligation and individuals having a professional responsibility to be adopters and contributors to Open Source is central to the future software industry. A lot of these companies have more resources at their disposal to help evolve the Open Source ecosystem and the community itself.  It can surface in many different ways but what Open Source needs the most are contributors and collaborators.

**Comment by ladyleet** [comment]
@ahmadnassri can we do a bullet point outline of what we want in this again?

**Comment by ladyleet** [comment]
@ahmadnassri just wanted to followup on this. maybe @mhdawson remembers what exactly we want for this article. :)

**Comment by ladyleet** [comment]
maybe this format will help:

What is it? 

Who’s it for? (Intended audience):

What’s the primary message you want that audience to come away with?: 

Summary of project (any more details on the above):

**Comment by ladyleet** [comment]
hey @ahmadnassri any progress yet? :P

**Comment by mhdawson** [comment]
@ladyleet what I remember is that it was to re-introduce the concept, talk about next steps/next meeting.

**Comment by ahmadnassri** [comment]
@ladyleet updated with details.

**Comment by ahmadnassri** [comment]
notes from today's meeting #131 

- should include "how to engage" guidelines for others who are interested, potentially related to comment: https://github.com/nodejs/user-feedback/issues/122#issuecomment-459927397 on listing existing members.

**Comment by ladyleet** [comment]
thank you for this @ahmadnassri !

**Comment by ladyleet** [comment]
@ahmadnassri thoughts on this draft? feel free to edit or talk about what needs to be added, etc. https://docs.google.com/document/d/1TYaj3E-3ojHZ6IIWTzbgWYabDmQnK8EF6LvmKPn480c/edit

// @mhdawson @dshaw

**Comment by mihaiep** [comment]
Hi, are we sure we want this name "Node Enterprise Feedback Group" ? In my opinion will create confusion with the current User Feedback. Why not only Node Enterprise, or Node Enterprise Advisory (the old name)? Thanks

**Comment by mhdawson** [comment]
In terms of the name how about 'Enterprise User Feedback sub-group', with the sub-group being the signal that it's its part of the larger user feedback working group.

**Comment by mhdawson** [comment]
Added some comments on the doc @ladyleet

**Comment by ahmadnassri** [comment]
How about:

> Node User Feedback Group: Enterprise Chapter

**Comment by ladyleet** [comment]
hey all! i put this through editing internally. check it out?

**Comment by ahmadnassri** [comment]
blog post is live: https://medium.com/@nodejs/introducing-the-node-js-enterprise-focus-group-312ff9f49aaa
