### ISSUE TITLE
Node.JS  May 9, 2019 Portland talk

### ISSUE THREAD

**Issue by mihaiep** [nodejs/user-feedback#128]
Agenda now is open: we do have Intel interested in a demo/talk to accelerate networking.

**Comment by mihaiep** [comment]
We are targeting PDX meet-up/talk on May 9, 2019.

**Comment by mihaiep** [comment]
Confirmed participation: Dan Shaw, James Snell

**Comment by WaleedAshraf** [comment]
If there any link for the talk/event for agenda and details?

**Comment by mihaiep** [comment]
Not yet. This issue was opened for tracking/ per our last Friday meet. Dan Shaw and James will be in Portland,OR and some Intel folks are interested. thanks

**Comment by mihaiep** [comment]
We have issue #151 opened. Closing this.
