### ISSUE TITLE
Where can we find the results from the Node.js Survey in past years?

### ISSUE THREAD

**Issue by mikehostetler** [nodejs/user-feedback#14]
As discussed on the #6 meeting on 2017-12-01, it would be great to get the results from prior Node.js User Survey's for this group to analyze and help direct our focus efforts going forward.

This thread was created to track and address the work required to make that happen.  There are understood security and privacy concerns that the Foundation has already solved.  Given that most of the new members of this group aren't yet aware of those existing procedures, this thread is also to help us track on those so we don't improperly handle any data.

Open Questions:
* Security Concerns around sharing this data
* Obfuscating private information
* Who from this working group needs access? Who can summarize and provide results back in a publicly consumable form?

**Comment by bnb** [comment]
cc @zibbykeaton - do you know if there is any specific place that we can get semi-raw data from? 🤔

**Comment by ZibbyKeaton** [comment]
Adding @hackygolucky and @gtewallace to this thread. They manage the survey and would have this information for you.
