### ISSUE TITLE
POSTPONED Node.js User Feedback Session - 2019-06-20 - Virtual - Enterprise Focus Group

### ISSUE THREAD

**Issue by ahmadnassri** [nodejs/user-feedback#161]
Suggest to postpone the scheduled "Enterprise Focus Group" session on June 20th, and either reclaim the time for a regular user-feedback session: https://github.com/nodejs/user-feedback/issues/160

or simply pick a new date in July.

**Comment by joesepi** [comment]
I am not able to make this time slot today unfortunately.
