### ISSUE TITLE
[PLANNING] User Feedback Meeting Cadence

### ISSUE THREAD

**Issue by dshaw** [nodejs/user-feedback#2]
During the bootstrap phase of this project, we will need to meet fairly regularly to maintain momentum.

@mhdawson has agreed to act as the champion for this project. Thank you, Michael. He will provide guidance and feedback and act as our representative in the CommComm. Additionally, he will assist with getting our meetings on a the Node.js Foundation project calendar and help setup the Hangout.

1) CommComm is meeting every 2 weeks and the next one is November 9th. Would @nodejs/user-feedback team members prefer:
  a) Meetings on the same week as CommComm meetings or 
  b) Meetings on alternating weeks from the CommComm

**Comment by mhdawson** [comment]
I'd suggest alternating.

**Comment by dshaw** [comment]
@nodejs/user-feedback I'd love to hear from you. Especially my co-organizers @mikehostetler and @williamkapke. See http://nodejs.org/calendar for details.  I recommend adding it to your calendaring app if you haven't already.

**Comment by mikehostetler** [comment]
I'd prefer alternating as well. I'm actively moving some things around on my schedule to make this a priority.  Looking forward to it!

**Comment by dshaw** [comment]
@mhdawson Is there a logic to the times selected for meetings? If so, can you point me to the guidelines?

**Comment by dshaw** [comment]
I created a Doodle to select a date and time for the first formal meeting #6: https://doodle.com/poll/96r9czpw6x9ds7zg
Note times are in Pacific Time if that's not obvious.

/cc @mikehostetler @williamkapke @mihaiep @jasnell @mhdawson

**Comment by mikehostetler** [comment]
Filled out the Doodle. In general, Wednesday mornings and Friday's are best as I work from home those days. Tuesday & Thursday are the worst, as those days I travel into the city.

**Comment by mhdawson** [comment]
Oops I assumed it was going to be every 2 weeks at the same date/time as the previous one so I added to the foundation calendar at that time.  Will update once we agree on the real time :)

**Comment by mhdawson** [comment]
Node for me it said: All times displayed in America/New York

So looks like you enable timezone support and we should each see in our own timezone ?

**Comment by mhdawson** [comment]
Filled out the doodle.  @dshaw in terms of choosing the time the only logic so far has been:

1) try to find a time that is good for all members
2) if no good time exists for all members, rotate the meeting so that members can attend a reasonable subset of the meetings.

**Comment by mhdawson** [comment]
Also regular meetings are best (even if the time rotates on a fixed cycle). Having it be different every time is too much work and often means you don't get enough responses to the doodle in time.

**Comment by dshaw** [comment]
Thank you, @mhdawson. We are aligned.

It looks like Friday is going to be our best time to meet. Now that we have established this single instance. I'd like to get your feedback on turning this into a regular cadence so @mhdawson can add this to the Node.js Calendar. I have added calendar invites for @mikehostetler @williamkapke @mihaiep @mhdawson with recurring instances occurring every 2 weeks.

Per the [Doodle](https://doodle.com/poll/96r9czpw6x9ds7zg#table), there are 3 times:
1) [17:00 UTC](https://www.wolframalpha.com/input/?i=2017-12-01+17:00+UTC) / noon ET / 11am CT / 9am PT
2) [18:00 UTC](https://www.wolframalpha.com/input/?i=2017-12-01+18:00+UTC) / 1pm ET / noon CT / 10am PT
3) [21:00 UTC](https://www.wolframalpha.com/input/?i=2017-12-01+21:00+UTC) / 4pm ET / 3pm CT / 1pm PT

Let's choose one.

**Comment by dshaw** [comment]
My preference is 1. 9am PT.

**Comment by mikehostetler** [comment]
11am CT / 9am PT is great for me as well.

**Comment by dshaw** [comment]
Grand.

@mhdawson: Is 1. 17:00 UTC / noon ET / 11am CT / 9am PT on Friday's something you can commit to?

@williamkapke: I know you are unavailable on 12/1 for the next meeting. Have a look at 12/15 and beyond. Is 1. 17:00 UTC / noon ET / 11am CT / 9am PT generally a good time for you?

**Comment by williamkapke** [comment]
I'll be honest- I'll probably be at Starbucks at that time & still in a morning daze. But then I'll remember while I'm there and rush back and be late.

If you can excuse my likely absentminded tardiness- I'm 👍

**Comment by dshaw** [comment]
We selected 1. 17:00 UTC / noon ET / 11am CT / 9am PT to get things started.
