### ISSUE TITLE
Participation and Node.js Community session at Index 2018

### ISSUE THREAD

**Issue by mhdawson** [nodejs/user-feedback#29]
See https://github.com/nodejs/admin/issues/44

On the suggested agenda is:

End user feedback session (as a way to bolster the work in https://github.com/nodejs/user-feedback)

@dshaw mentioned we was planning to be at Index.  We need to discuss/document what/how we'd like to structure the session.

**Comment by dshaw** [comment]
@mhdawson Is there a good forum to reach out to attendees to invite them?

**Comment by mhdawson** [comment]
Talked to the organizers, lets put together a short invite text and then we'll follow up with them to tweet out etc.

**Comment by bnb** [comment]
This is now complete, but I think something should be logged in this repo about the in-person event. @dshaw or @mhdawson would you like to try to define what that would be? I'm not really sure what the best approach is.

**Comment by dshaw** [comment]
@bnb: @mihaiep [PRed minutes for the session](https://github.com/nodejs/user-feedback/pull/33). If you'd like to see more content from that session show up somewhere, then I'll add a topic to Friday's meeting agenda.

**Comment by mihaiep** [comment]
One comment: the PR is made for the Public User -Benchmark meeting from 2.16.2018, couple of days before Index 2018. 
Meeting notes from the open session from Index 2018, will be available next days, and will be another PR. Hope this help.

**Comment by dshaw** [comment]
@mihaiep Thanks for clarifying.

**Comment by bnb** [comment]
Looks great @mihaiep. I think this issue can be closed now?
