### ISSUE TITLE
Feedback requested on user-feedback README

### ISSUE THREAD

**Issue by dshaw** [nodejs/user-feedback#3]
@nodejs/user-feedback @mhdawson Please review [README.md](https://github.com/nodejs/user-feedback/blob/master/README.md).

I created an initial README for this repo and expected to get prompted to go through the Pull Request workflow. Perhaps since there were no documents yet in the repo, that wasn't an option. My apologies for the direct commit.

Please review https://github.com/nodejs/user-feedback/commit/3bd642959ec58545dc156879de7b3b59b25909b5 and provide feedback. I'm specifically look for lazy consensus of at least 3 individuals in @nodejs/user-feedback ( 👍  ) and no nos ( 👎 ). Thank you.

**Comment by dshaw** [comment]
Recording one 👍 from @williamkapke: https://github.com/nodejs/user-feedback/commit/3bd642959ec58545dc156879de7b3b59b25909b5#commitcomment-25400698

Thank you.

**Comment by mhdawson** [comment]
+1 from me as well.  There was one minor comment that is worth integrating but overall LGTM

**Comment by hackygolucky** [comment]
If it can be done fairly quickly, I'd like to see a next-round PR that walks people through what the User Feedback Initiative -is- and a few of the projects that are currently being discussed(the work @dshaw and @jasnell are each driving along with our survey work). 

The more explanation and projects we share, the more likely people will light up if they think it is something they have insight to contribute on.

**Comment by bnb** [comment]
Generally looks like a good first pass, I have some nits around the language (making it more welcoming and open) - but those can be addressed a bit later in other PRs.

Only other feedback is that generally when people are standard members we don't assign a role to them. Totally +1 to having "advisor" there if that's how the Team wants to label normal members, but in my experience so far with the Node.js org an advisory role has been a less involved roll that is pulled in when there's a specific question. 

Not sure if that was the intended meaning with adding that label to @hackygolucky and myself or not - if not, no worries.

**Comment by dshaw** [comment]
Capturing the "roles" is to enable wayfinding.

Referring to both @bnb and @hackygolucky as advisors is because both expressed that you would not have time to be actively involved.

Noting that we still have not achieved consensus.

**Comment by mikehostetler** [comment]
Replied to the commit with 👍 . For sake of clarity replying here as well.

I also added a PR to include my email address in #7

**Comment by mhdawson** [comment]
still +1 from me.

**Comment by dshaw** [comment]
This issue is _almost_ ready to close. #4 captures most of the action items Tierney brought up. I'm leaving this open until I create an issue covering [Tracy's requested additions](https://github.com/nodejs/user-feedback/issues/3#issuecomment-342873274).
