### ISSUE TITLE
Plan public Node.js User Feedback session for 2018-03-30

### ISSUE THREAD

**Issue by dshaw** [nodejs/user-feedback#38]
- Attendees:
  * @nodejs/user-feedback 
  * @boneskull - Mocha
  * @thelarkinn - webpack
  * @iarna - npm
  * @jchip - Electrode, End User representative
  * @nodejs/modules 
- Topics:
  * Describe how your Tooling leverages Node.js.
  * Why do you use Node.js for Tooling?
  * What's working in the Node.js tooling ecosystem?
  * What isn't working in the Node.js tooling ecosystem?
  * What's new that could impact Node.js?
- Desired outcomes:
  * Greater insight into the needs of Tooling authors needs

**Comment by dshaw** [comment]
Topics:
* What's working in the Node.js tooling ecosystem?
* What isn't working in the Node.js tooling ecosystem?

**Comment by dshaw** [comment]
Attendees:
* Invite @jchip of Walmart for end user prospective.

**Comment by dshaw** [comment]
Topics (for feedback):
* Invite Node.js tooling ecosystem folks to discuss user feedback -
 https://github.com/nodejs/node/issues/19079

**Comment by dshaw** [comment]
Topic:
- Using N-API

**Comment by dshaw** [comment]
Topic:
* Is there anything the Node.js Project and/or the Node.js Foundation could do to better support your needs?

**Comment by dshaw** [comment]
Invite @kborchers and JS Foundation representatives.

**Comment by boneskull** [comment]
the sean larkin you want is @TheLarkInn

**Comment by dshaw** [comment]
The first and only Sean Larkin. Thanks, @boneskull.

**Comment by jchip** [comment]
@dshaw I am traveling to China 3/29 so I won't be able to attend this time.  Thanks.

**Comment by kellyselden** [comment]
I can attend on behalf of the @ember-cli team.

**Comment by uttampawar** [comment]
Dan, I'll attend for team Intel. Is there timing information somewhere?

**Comment by bnb** [comment]
Closing, since this is a past meeting. Thanks for attending everyone! We look forward to continuing to work with y'all more in the future.
