### ISSUE TITLE
Add CoC, CONTRIBUTING.md, and Repo Accountability

### ISSUE THREAD

**Issue by bnb** [nodejs/user-feedback#4]
For https://github.com/nodejs/community-committee/pull/167 to land, we need a few things to land here first:

- A Code of Conduct - since this is not an independent WG, the [standard Code of Conduct](https://github.com/nodejs/community-committee/blob/master/CODE_OF_CONDUCT.md) structure should be used. Additionally, I _believe_ the team needs to ensuring that all members do not object to the Code of Conduct - or, at least, let them know that it is being added.
- CONTRIBUTING.md - adding in a contributing guide for those contributing/interested in participating, even if it's a simple doc.
- Accountability to CommComm - add a section marking accountability to the CommComm (an example can be found in the [Evangelism WG](https://github.com/nodejs/evangelism/blob/master/README.md#governance-and-contributing) README.md)

**Comment by dshaw** [comment]
@bnb @mihaiep has raised his hand to volunteer to add these items. I have added him as a collaborator under settings to enable that with write permissions. Is that in line with expectations on how someone is added?

**Comment by dshaw** [comment]
@mihaiep After reviewing https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md , I think I need to remove you as a Collaborator for now as a matter of process. This means that I won't be able to assign this issue to you, an unfortunate side effect due to GitHub policy. Performing the tasks above will definitely help move toward earning Collaborator status.

**Comment by bnb** [comment]
@dshaw @mihaiep although the GitHub issue can't be assigned to @mihaiep, the contribution and initiative should absolutely be welcomed and is absolutely non-trivial.  Thanks for raising your hand @mihaiep 🙏

**Comment by bnb** [comment]
@dshaw @mhdawson  can you confirm that this is complete? Looking over the repo, it looks like it is - but I'd like to get your feedback before closing this and merging https://github.com/nodejs/community-committee/pull/167

**Comment by dshaw** [comment]
I added the final item so we can land this. with #11. Let's get it approved!
