### ISSUE TITLE
Tracking PR#31:Add templates for the user-feedback repo 

### ISSUE THREAD

**Issue by mihaiep** [nodejs/user-feedback#42]
Opening this for tracking [#31](https://github.com/nodejs/user-feedback/pull/31). 
"@mihaiep to add the templates you want to open a PR in this repo: https://github.com/mhdawson/create-node-meeting-artifacts

and create files in the https://github.com/mhdawson/create-node-meeting-artifacts/tree/master/templates directory. You can pick one of the existing ones (ex commcomm) and copy the templates (4 files) *_commcomm and then edit as per: https://github.com/mhdawson/create-node-meeting-artifacts/blob/master/TEMPLATES_DOCUMENTATION.md.

If you can take a first cut and open a PR I can then test and fixup to get them working."

**Comment by mihaiep** [comment]
thank you @bnb, Tierney for helping me cleaning the old unwanted commits.

**Comment by mihaiep** [comment]
#31

**Comment by mihaiep** [comment]
PR(s) created  [23](https://github.com/mhdawson/create-node-meeting-artifacts/pull/23), [24](https://github.com/mhdawson/create-node-meeting-artifacts/pull/24),[25](https://github.com/mhdawson/create-node-meeting-artifacts/pull/25), [26](https://github.com/mhdawson/create-node-meeting-artifacts/pull/26)

**Comment by mhdawson** [comment]
Ok landed. Should create meeting next Monday for the meeting the Friday of that week.

@dshaw Note that I see 2 tags being used neuf-agenda and user-feedback-agenda.  The generated doc will only include those tagged neuf-agenda.

**Comment by mihaiep** [comment]
Templates are [**here**](https://github.com/mhdawson/create-node-meeting-artifacts/tree/master/templates).

**Comment by mhdawson** [comment]
They are landed, next meeting should auto generate.

**Comment by dshaw** [comment]
Thank you, @mihaiep and @mhdawson, for getting this setup.
