### ISSUE TITLE
Public User Feedback request - European General User Feedback at WorkerConf

### ISSUE THREAD

**Issue by dshaw** [nodejs/user-feedback#56]
@bmeurer has invited the User Feedback team to host public User Feedback session like we did at IndexConf. @dshaw be in Italy in June, so he can host.

https://twitter.com/dshaw/status/985963240663400449

https://worker.sh/

**Comment by bnb** [comment]
Would love to come to this if at all possible 🤔

**Comment by ladyleet** [comment]
@dshaw @bnb i'll be there too speaking with @benlesh! // @annmarietonog @mrhinkle

**Comment by dshaw** [comment]
@mihaiep Unfortunately, there was very low turnout. No recording. We did have a constructive session speaking with local organizers.
