### ISSUE TITLE
2018-08-16 End User Feedback Meeting - Enterprise Use Case

### ISSUE THREAD

**Issue by dshaw** [nodejs/user-feedback#81]
# 2018-08-16 End User Feedback Meeting - Enterprise Use Case

## Time

Thursday, 2018-08-16 at 17:00 UTC / noon ET / 11am CT / 9am PT

## Links

* **Minutes Doc**: TBD
* **Previous Minutes Doc**: TBD

## Agenda

This is a public User Feedback meeting with invited participants focused on a specific topic, the Enterprise Use Case for Node.js. Please feel free to propose items for discussion to be added to the agenda below.

* Topics:
  - Round table Introductions:
    - Who are you?
    - Where do you work?
    - What do you do?
    - Describe your Node.js. Enterprise Use Case
  - What's working and what isn't for Node.js in the Enterprise?
    - ✋ _Raise hand to join the discussion_
* Open feedback forum

## Invited
* User Feedback team members
  * Dan Shaw (@dshaw - User Feedback Champion, Mentorship, CommComm)
  * Mihai Ene-Pietrosanu (@mihaiep, User Feedback)
  * Michael Dawson (@mhdawson - User Feedback, CommComm, TSC Chair)
  * Tierney Cyren (@bnb - User Feedback, CommComm Chair)

* Enterprise Use Case Representatives
  * Ahmad Nassri (@ahmadnassri - Principal Architect, TELUS) - _Enterprise Feedback Lead_
  * Adrian Maurer (@adrianmaurer - Director of Consulting Services and Emerging Technology Practice Lead, CGI)
  * Joel Chen (@jchip - Principal Architect @WalmartLabs)

## Public participation

The Node.js project live streams meetings so anyone can tune in. Everyone is invited to participate in the live chat. The stream will start playng at https://www.youtube.com/c/nodejs+foundation/live once we go live.

There's usually a short cat-herding time at the start of the meeting and occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and we'll be online shortly. ❤️

## Joining the meeting

Join link for invited members and participants: https://zoom.us/j/353642832

There is a standing invitation for all @nodejs/TSC and @nodejs/community-committee members to attend.

**Comment by mhdawson** [comment]
Unfortunately, I'm away on holiday the week of this meeting but I'll follow up afterwards to see if there is anything @ahmadnassri needs to keep the momentum going :)

**Comment by jchip** [comment]
Hi, I will join the meeting.  thanks.

**Comment by dshaw** [comment]
Participate in the live session: https://zoom.us/j/353642832

**Comment by mihaiep** [comment]
Live now https://www.youtube.com/watch?v=mDE6G6I180w

**Comment by ahmadnassri** [comment]
minutes doc: https://docs.google.com/document/d/187IFxgsW8YKoJvKF0Kv27HKaEBFm99WYsbzht32uHVg/edit

**Comment by bnb** [comment]
Going to close this, since the meeting is in the past ❤️
