### ISSUE TITLE
September 2018 Node.js Online Meetup

### ISSUE THREAD

**Issue by dshaw** [nodejs/user-feedback#90]
Meetup: https://www.meetup.com/Nodejs-Online-Meetup/

Meetup Link for the event: https://www.meetup.com/Nodejs-Online-Meetup/events/srcvdqyxmbqb/

Join and participate: https://zoom.us/s/997723299

Watch live on YouTube: https://www.youtube.com/c/nodejs+foundation/live

Agenda:
  - 5pm ET - Gather and socialize
  - 5:30pm to 6:30pm ET - Talks
  - 6:30pm to 7:00pm - Open discussion

Invited speakers (15-20 minutes each):
* @mhdawson - Introduction to Node.js Initiatives, working groups and teams and how to get involved
* @Trott - A Response To “Design Mistakes in Node”

Partner Meetup groups:
_To extend the meetup experience, we are inviting local communities to host in-person sessions._
* SFNode Meetup
* Toronto JS

**Comment by Trott** [comment]
@dshaw Can you edit the title and/or description text to include the date? I see by clicking through to the link that it's September 12, but it would be good to have it right here I think.

**Comment by mhdawson** [comment]
Agreed, I was looking for the date as well.

**Comment by mihaiep** [comment]
Live now: https://www.youtube.com/watch?v=_Thhx57-5Co

**Comment by mihaiep** [comment]
Discussions: https://www.meetup.com/Nodejs-Online-Meetup/discussions/

**Comment by mhdawson** [comment]
Link to slides from my presentation https://github.com/mhdawson/presentations/blob/master/2018/NodejsUserFeedbackMeetup%20-%20Sep%202018%20-%20Getting%20Involved%20-%20WGs%20and%20Strategic%20initiatives.pdf

**Comment by ZibbyKeaton** [comment]
I mentioned this is an email to @mhdawson but I think this is something that we should collaborate on to try to build up this series and get a larger audience for it. I know we will not have one in October, but if we have a working calendar on upcoming events and topics, I can start to flesh out a promotional plan on it and we can coordinate on objectives and results that we would like to see coming out of this initiative. Maybe we can make this a topic for our next CommComm meeting or I can join a user-feedback group meeting?

**Comment by Trott** [comment]
(Seems like this should be closed and other issues opened going forward. Feel free to comment or re-open if I'm wrong about that!)
