### ISSUE TITLE
Request to join the User Feedback Committee

### ISSUE THREAD

**Issue by cfanoulis** [nodejs/user-feedback#98]
Good evening. With the following, I'd like to request to join the Committe. Please inform me of the procedure.

**Comment by WaleedAshraf** [comment]
Hi @cfanoulis 

There is some related info in [CONTRIBUTING.md](https://github.com/nodejs/user-feedback/blob/master/CONTRIBUTING.md)

**Comment by mhdawson** [comment]
@cfanoulis I'd suggest starting by attending the next meeting and reading through the repo to catch on the existing work in the team.

**Comment by cfanoulis** [comment]
closing as there is no action to be taken. Expect me on the next meetup tho :^)
